services:
  alin-monitor:
    build: .
    container_name: alin-monitor
    restart: unless-stopped

    environment:
      SOPS_AGE_KEY_FILE: /run/secrets/age-key

    volumes:
      - ./data:/app/data
      - ./config:/app/config

    secrets:
      - age-key

secrets:
  age-key:
    file: ${AGE_KEY_FILE}
